{{- range .Values.services.kafka }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    cozystack.io/ui: "true"
spec:
  chart:
    spec:
      chart: kafka
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.2.2
  interval: 1m0s
  timeout: 5m0s
  values:
    {{- toYaml .values | nindent 4 }}
{{- end }}
