{{- range .Values.services.kubernetes }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    cozystack.io/ui: "true"
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.8.0
  interval: 1m0s
  timeout: 5m0s
  values:
    {{- toYaml .values | nindent 4 }}

{{- if .copySecrets }}
---
### COPY SECRET TO TENANT CLUSTER:
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-{{ .name }}-copy-secrets
  namespace: {{ $.Values.namespace }}
spec:
  targetNamespace: default
  storageNamespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/secret
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: main
        namespace: tenant-root
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  values:
    secret:
      metadata:
        name: secrets
        namespace: default
  valuesFrom:
    {{- range $secret := .copySecrets }}
    - kind: Secret
      name: {{ $secret.name }}
      #optional: true
      targetPath: {{ $secret.targetPath }}
      valuesKey: {{ $secret.valuesKey }}
    {{- end }}
  kubeConfig:
    secretRef:
      name: kubernetes-{{ .name }}-admin-kubeconfig
      key: super-admin.conf
  dependsOn:
  - name: kubernetes-{{ .name }}
{{- end }}
{{- if .fluxSync }}
---
### COPY SECRET TO TENANT CLUSTER:
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-{{ .name }}-deploy-application
  namespace: {{ $.Values.namespace }}
spec:
  targetNamespace: default
  storageNamespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: flux2-sync
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      version: '1.9.0'
  interval: 1m0s
  timeout: 5m0s
  kubeConfig:
    secretRef:
      name: kubernetes-{{ .name }}-admin-kubeconfig
      key: super-admin.conf
  dependsOn:
  - name: kubernetes-{{ .name }}
  {{- with .fluxSync.values }}
  values:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: {{ $.Values.namespace }}
spec:
  interval: 5m0s
  url: https://fluxcd-community.github.io/helm-charts
