apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.metadata.name }}
  namespace: {{ .Values.secret.metadata.namespace }}
data:
{{- $data := .Values.secret.data | default (dict) -}}
{{- if $data }}
  {{- range $name, $value := $data }}
  {{ $name }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }} 
